version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.taipy
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./knowledge_base_data:/app/knowledge_base_data
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./logs:/app/logs
    environment:
      - USE_TAIPY=${USE_TAIPY:-true}
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: